name: Release

on:
  workflow_dispatch:
#  push:
#    branches:
#    - master
#    paths:
#    - '**/*.tf'
#    - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    # Skip running release workflow on forks
    if: github.repository_owner == 'MaciekLeks'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 19.0.5
      #        extra_plugins: |
      #          @semantic-release/changelog@v6.0.3
      #          @semantic-release/git@v10.0.1
      #          @semantic-release/github@v9.0.4
      #          conventional-changelog-conventionalcommits@4.6.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
